export interface GameImage {
  id: string;
  url: string;
  isAI: boolean;
  description: string;
  tip: string;
  difficulty: "easy" | "medium" | "hard";
}

const AI_IMAGES: GameImage[] = [
  {
    id: "ai_1",
    url: "https://image.pollinations.ai/prompt/photorealistic%20portrait%20of%20a%20beautiful%20woman%20blue%20eyes%20studio%20lighting?width=512&height=512&seed=7391&model=flux&nologo=true",
    isAI: true,
    description: "Generated by Flux AI. The skin texture and eyes are unusually perfect.",
    tip: "AI portraits often have flawless, plastic-looking skin and symmetrical eyes that glow slightly.",
    difficulty: "medium",
  },
  {
    id: "ai_2",
    url: "https://image.pollinations.ai/prompt/epic%20mountain%20landscape%20golden%20hour%20dramatic%20clouds%20ultra%20realistic?width=512&height=512&seed=2847&model=flux&nologo=true",
    isAI: true,
    description: "AI-generated landscape. The clouds and lighting are too dramatic and uniform.",
    tip: "AI landscapes tend to have unrealistically perfect lighting and overly dramatic skies.",
    difficulty: "hard",
  },
  {
    id: "ai_3",
    url: "https://image.pollinations.ai/prompt/old%20man%20weathered%20face%20deep%20wrinkles%20wise%20eyes%20natural%20light?width=512&height=512&seed=5523&model=flux&nologo=true",
    isAI: true,
    description: "Generated by AI. Notice how the wrinkles follow unnaturally uniform patterns.",
    tip: "AI struggles with consistent wrinkle depth and ear/hair detail at the edges.",
    difficulty: "medium",
  },
  {
    id: "ai_4",
    url: "https://image.pollinations.ai/prompt/cute%20golden%20retriever%20puppy%20in%20garden%20sunlight%20professional%20photo?width=512&height=512&seed=9102&model=flux&nologo=true",
    isAI: true,
    description: "AI-generated dog photo. The fur texture looks too soft and the background blurs unnaturally.",
    tip: "AI animal fur often lacks the individual strand detail of a real photo.",
    difficulty: "hard",
  },
  {
    id: "ai_5",
    url: "https://image.pollinations.ai/prompt/young%20man%20confident%20smile%20natural%20outdoor%20portrait%20bokeh?width=512&height=512&seed=3318&model=flux&nologo=true",
    isAI: true,
    description: "AI portrait. Look at the teeth — too perfectly uniform, and the collar shows warping.",
    tip: "Teeth, collars, and glasses frames are common failure points for AI-generated faces.",
    difficulty: "easy",
  },
  {
    id: "ai_6",
    url: "https://image.pollinations.ai/prompt/cozy%20cat%20sitting%20windowsill%20soft%20morning%20light%20warm%20atmosphere?width=512&height=512&seed=6647&model=flux&nologo=true",
    isAI: true,
    description: "AI-generated cat photo. The whiskers and fur edges blend unnaturally into the background.",
    tip: "AI-generated animals often have whisker artifacts and fur that blends oddly at edges.",
    difficulty: "medium",
  },
  {
    id: "ai_7",
    url: "https://image.pollinations.ai/prompt/futuristic%20city%20skyline%20night%20neon%20lights%20rain%20reflections%20ultra%20detailed?width=512&height=512&seed=8834&model=flux&nologo=true",
    isAI: true,
    description: "AI city scene. The architecture repeats unnaturally and signs contain gibberish letters.",
    tip: "Look at signs and text in AI images — they almost always contain illegible or nonsense characters.",
    difficulty: "easy",
  },
  {
    id: "ai_8",
    url: "https://image.pollinations.ai/prompt/tropical%20waterfall%20jungle%20sunbeams%20through%20trees%20ultra%20realistic%20photography?width=512&height=512&seed=4459&model=flux&nologo=true",
    isAI: true,
    description: "AI jungle scene. The water flow pattern and leaf repetition reveal its synthetic origin.",
    tip: "AI water often looks frozen or moves in unnatural directions. Leaves tend to repeat.",
    difficulty: "hard",
  },
  {
    id: "ai_9",
    url: "https://image.pollinations.ai/prompt/woman%20laughing%20candid%20moment%20park%20natural%20sunlight%2035mm%20film?width=512&height=512&seed=1173&model=flux&nologo=true",
    isAI: true,
    description: "AI portrait styled to look candid. The hair strands merge oddly and the background has soft artifacts.",
    tip: "AI tries to mimic candid photos but background objects often lose coherence.",
    difficulty: "hard",
  },
  {
    id: "ai_10",
    url: "https://image.pollinations.ai/prompt/professional%20chef%20cooking%20kitchen%20flames%20dramatic%20lighting%20action%20shot?width=512&height=512&seed=7720&model=flux&nologo=true",
    isAI: true,
    description: "AI action scene. Hands and fingers near objects are a giveaway — count the fingers.",
    tip: "AI notoriously struggles with hands. Extra fingers, merged digits, or wrong proportions are red flags.",
    difficulty: "easy",
  },
];

const REAL_IMAGES: GameImage[] = [
  {
    id: "real_1",
    url: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real portrait photograph. Notice the natural skin imperfections and authentic catchlights in the eyes.",
    tip: "Real portraits show natural asymmetry, subtle skin texture, and authentic background depth.",
    difficulty: "medium",
  },
  {
    id: "real_2",
    url: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real landscape photograph. The cloud formations and mountain erosion patterns are naturally irregular.",
    tip: "Real landscapes have inconsistent lighting and naturally chaotic details.",
    difficulty: "hard",
  },
  {
    id: "real_3",
    url: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real dog photo. Individual fur strands, wet nose texture, and eye reflection are genuine.",
    tip: "Real animal photos show individual hairs, authentic catch-lights, and natural imperfections.",
    difficulty: "hard",
  },
  {
    id: "real_4",
    url: "https://images.unsplash.com/photo-1529778873920-4da4926a72c2?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real cat photograph. The whiskers are individually distinct and the fur has natural directional variation.",
    tip: "Real cats have individually sharp whiskers and fur that flows in a consistent biological direction.",
    difficulty: "medium",
  },
  {
    id: "real_5",
    url: "https://images.unsplash.com/photo-1519046904884-53103b34b206?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real beach photograph. The wave patterns and sand texture are naturally chaotic.",
    tip: "Real water scenes show turbulent, unpredictable patterns. AI tends to make them too smooth.",
    difficulty: "hard",
  },
  {
    id: "real_6",
    url: "https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real city skyline photo. The buildings have authentic weathering and legible signs.",
    tip: "Real city photos have readable text on signs and buildings with authentic wear and asymmetry.",
    difficulty: "easy",
  },
  {
    id: "real_7",
    url: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real portrait. The skin pores, hair strands, and slight asymmetry are authentically human.",
    tip: "Real human portraits have natural facial asymmetry and skin with visible pores and texture.",
    difficulty: "medium",
  },
  {
    id: "real_8",
    url: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real forest path. The leaves show natural decay variations and the path has authentic wear.",
    tip: "Real nature photos show random variation in leaves, branches, and ground texture.",
    difficulty: "hard",
  },
  {
    id: "real_9",
    url: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real male portrait. The stubble, eye redness, and shirt wrinkles are all naturally imperfect.",
    tip: "Real men's portraits often show beard stubble with natural randomness and genuine eye texture.",
    difficulty: "medium",
  },
  {
    id: "real_10",
    url: "https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=512&h=512&fit=crop&q=80",
    isAI: false,
    description: "A real dog portrait. The eye reflection and individual fur strands confirm its authenticity.",
    tip: "Dog eyes in real photos show a natural world reflected inside the pupil. AI eyes often look glassy.",
    difficulty: "easy",
  },
];

export const ALL_GAME_IMAGES: GameImage[] = [...AI_IMAGES, ...REAL_IMAGES];
