/**
 * End-to-end tests: deep-link bounce page fallback behaviour
 *
 * The native auth bounce page is generated by buildNativeBounceHtml() in
 * server/routes.ts and served via the Google OAuth callback.  The page
 * immediately fires intent:// and guber:// deep-link navigation attempts, then
 * after 4 s shows a retry state; after a further 3 s on retry it shows a
 * Play Store state.  If the page is hidden before the timer fires (the OS
 * handed off to the native app) neither fallback state must appear.
 *
 * These tests hit the dedicated dev-only endpoint /api/test/deep-link-bounce
 * which calls the SAME buildNativeBounceHtml() function used in production.
 * Any change to that function is automatically reflected here.
 *
 * Navigation suppression:
 *   window.location.replace() with intent:// or guber:// causes headless
 *   Chromium to navigate away and destroy the page DOM.  Solution: fetch the
 *   real HTML from the server, replace every occurrence of
 *   "window.location.replace(" with "void(" (a valid no-op expression), then
 *   load the modified HTML via page.setContent().  Every other part of the
 *   template — DOM structure, CSS, timer constants, event wiring — comes
 *   directly from the server so regressions in buildNativeBounceHtml() are
 *   still caught.
 *
 * Run:
 *   npx playwright test e2e/deep-link-fallback.spec.ts
 */

import { test, expect } from "@playwright/test";

/** Primary fallback timeout baked into buildNativeBounceHtml(). */
const TIMEOUT_MS = 4000;

const BOUNCE_URL = "/api/test/deep-link-bounce";

/**
 * Fetch the real server-rendered bounce page HTML, suppress all
 * window.location.replace() calls so Playwright doesn't navigate away, then
 * load it into the page via setContent().
 */
async function loadBouncePage(page: import("@playwright/test").Page) {
  const NAVIGATE_MARKER = "window.location.replace(";

  const response = await page.request.get(BOUNCE_URL);
  expect(response.status()).toBe(200);

  let html = await response.text();

  expect(
    html,
    "server template must still contain window.location.replace( — update this test if the marker changed"
  ).toContain(NAVIGATE_MARKER);

  // Replace every window.location.replace(expr) with void(expr) — a valid JS
  // no-op that evaluates expr (a string) without triggering navigation.
  html = html.replaceAll(NAVIGATE_MARKER, "void(");

  await page.setContent(html, { waitUntil: "domcontentloaded" });
}

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 1: both fallback states are hidden on page load
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link fallback: #retry-state and #store-state are hidden immediately on load", async ({
  page,
}) => {
  await loadBouncePage(page);

  await expect(page.locator("#retry-state")).toBeHidden();
  await expect(page.locator("#store-state")).toBeHidden();
});

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 2: #retry-state becomes visible after 4 s when app is not installed
// The page stays open (gone stays false) so the timer shows the retry state.
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link fallback: #retry-state becomes visible after 4 s when the app cannot be opened", async ({
  page,
}) => {
  await loadBouncePage(page);

  await expect(page.locator("#retry-state")).toBeHidden();
  await expect(page.locator("#store-state")).toBeHidden();

  await page.waitForTimeout(TIMEOUT_MS + 800);

  await expect(page.locator("#retry-state")).toBeVisible();
  await expect(page.locator("#retry-btn")).toBeVisible();
  // store state is not shown yet — only after a second retry timeout
  await expect(page.locator("#store-state")).toBeHidden();
});

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 3: fallback stays hidden when visibilitychange fires before timeout
// A successful deep-link hand-off hides the browser tab.  gone=true prevents
// the timer callback from showing any fallback UI.
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link fallback: fallback stays hidden when visibilitychange fires before the timeout", async ({
  page,
}) => {
  await loadBouncePage(page);

  await expect(page.locator("#retry-state")).toBeHidden();

  // Simulate the OS handing off to the native app — page becomes hidden.
  await page.evaluate(() => {
    Object.defineProperty(document, "visibilityState", {
      configurable: true,
      get: () => "hidden",
    });
    document.dispatchEvent(new Event("visibilitychange"));
  });

  await page.waitForTimeout(TIMEOUT_MS + 800);

  await expect(page.locator("#retry-state")).toBeHidden();
  await expect(page.locator("#store-state")).toBeHidden();
});
