/**
 * End-to-end tests: deep-link bounce page behaviour
 *
 * The native auth bounce page is generated by buildNativeBounceHtml() in
 * server/routes.ts and served via the Google OAuth callback. It shows an
 * immediate "Open GUBER" button (user-gesture navigation — works in all Chrome
 * versions) and also fires an auto-attempt via window.location.replace() for
 * Chrome versions that allow custom-scheme navigation without a gesture.
 *
 * These tests hit the dedicated dev-only endpoint /api/test/deep-link-bounce
 * which calls the SAME buildNativeBounceHtml() function used in production.
 * Any change to that function is automatically reflected here.
 *
 * Navigation suppression:
 *   window.location.replace() with a guber:// scheme causes headless Chromium
 *   to navigate away. Solution: fetch the real HTML from the server, replace
 *   every occurrence of "window.location.replace(" with "void(" (a valid no-op),
 *   then load the modified HTML via page.setContent(). The button's
 *   window.location.href assignment is also suppressed for test isolation.
 *   Every other part of the template comes directly from the server.
 *
 * Run:
 *   npx playwright test e2e/deep-link-fallback.spec.ts
 */

import { test, expect } from "@playwright/test";

const BOUNCE_URL = "/api/test/deep-link-bounce";

/**
 * Fetch the real server-rendered bounce page HTML, suppress all navigation
 * calls so Playwright doesn't leave the page, then load it via setContent().
 */
async function loadBouncePage(page: import("@playwright/test").Page) {
  const NAVIGATE_MARKER = "window.location.replace(";

  const response = await page.request.get(BOUNCE_URL);
  expect(response.status()).toBe(200);

  let html = await response.text();

  expect(
    html,
    "server template must still contain window.location.replace( — update this test if the marker changed"
  ).toContain(NAVIGATE_MARKER);

  // Suppress window.location.replace() so Playwright doesn't navigate away.
  html = html.replaceAll(NAVIGATE_MARKER, "void(");
  // Suppress button click navigation too.
  html = html.replaceAll("window.location.href = deepLink", "void(deepLink)");

  await page.setContent(html, { waitUntil: "domcontentloaded" });
}

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 1: Open button is immediately visible on load
// The button is the primary call-to-action and must be visible as soon as
// the page loads — not hidden behind a timer.
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link bounce: #open-btn is visible immediately on load", async ({ page }) => {
  await loadBouncePage(page);
  await expect(page.locator("#open-btn")).toBeVisible();
});

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 2: Auto-attempt marker is present in the server HTML
// The HTML must include window.location.replace( so the auto-attempt fires
// on Chrome versions that allow custom-scheme navigation without a gesture.
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link bounce: HTML contains auto-attempt window.location.replace(", async ({ page }) => {
  const response = await page.request.get(BOUNCE_URL);
  const html = await response.text();
  expect(html).toContain("window.location.replace(");
  expect(html).toContain("guber://auth-success");
});

// ─────────────────────────────────────────────────────────────────────────────
// Scenario 3: Page is stable after 5 s — no timer-based fallback states
// The new design has no timers that hide or alter content, so the button must
// still be visible and no unexpected elements must have appeared.
// ─────────────────────────────────────────────────────────────────────────────
test("deep-link bounce: page is stable after 5 s (no timer-driven state changes)", async ({ page }) => {
  await loadBouncePage(page);

  await expect(page.locator("#open-btn")).toBeVisible();

  await page.waitForTimeout(5000);

  // Button is still visible — no timer removed or hid it.
  await expect(page.locator("#open-btn")).toBeVisible();
  // No old timer-state elements exist in the DOM.
  await expect(page.locator("#retry-state")).toHaveCount(0);
  await expect(page.locator("#store-state")).toHaveCount(0);
});
